[tool.poetry]
name = "sorep"
version = "0.1.0"
description = "Spectral Operator Representations"
authors = ["Austin Zadoks <austin.zadoks@protonmail.com>"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "<2.0"
scipy = "^1.14.0"
ase = "^3.23.0"
scikit-learn = "^1.5.1"
imbalanced-learn = "^0.12.3"

[tool.poetry.group.dev.dependencies]
matplotlib = "^3.9.0"
tqdm = "^4.66.4"
pytest = "^8.2.2"
yapf = "^0.40.2"
ipython = "^8.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
